# Generated by Django 5.1.6 on 2026-04-11 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aitool",
            name="format_type",
            field=models.CharField(
                default="web_tool",
                help_text="Digital object format e.g. web_tool, api, plugin",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="aitool",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="SEO-style keyword string (complements M2M tags)",
                max_length=300,
            ),
        ),
        migrations.CreateModel(
            name="Tutorial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.URLField(max_length=500)),
                ("description", models.TextField(blank=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutorials",
                        to="catalog.aitool",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(db_index=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmark_entries",
                        to="catalog.aitool",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session_key", "tool"),
                        name="catalog_bookmark_session_tool_uc",
                    )
                ],
            },
        ),
    ]
